<a href="https://colab.research.google.com/github/litlife8582/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [125]:
import numpy as np

Creation of numpy arrays and some basic functions


list_name={a,b,c,d}

array_name=np.array(list_name)

np.array-> converts data structures to numpy list

In [126]:
list1={1,2,3,4,5,6}
array1=np.array(list1)
print(array1)

tuple1=(1,2,3,4,5)
arr=np.array(tuple1)
print(arr)

{1, 2, 3, 4, 5, 6}
[1 2 3 4 5]


In [127]:
#creating a 2D array or list of lists
array2=np.array([[5,7],[6,8]])
print(array2)

[[5 7]
 [6 8]]


np.zeros- creates a two dimentional array with(row,coloumn) and zero as its elements

In [128]:
array3=np.zeros((2,10))
print(array3)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


np.full((rows,columns),element)- 2d array made of gven element

In [129]:
array4=np.full((2,10),6)
print(array4)

[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


Creating Multidimentional Arrays using array creation functions

1D array
np.arange and np.linspace


np.arange

Parameters:

1.start (optional): The starting value of the sequence (default is 0).

2.stop (required): The end value (exclusive).

3.step (optional): The step size between values (default is 1).

4.dtype (optional): The data type of the output array.

Syntax of np.arange function:

numpy.arange([start, ]stop, [step, ], dtype=None)


In [130]:
array5=np.arange(2,10,dtype=float)#prints an array of elements having float datatype with default step size 1
print(array5)

#with stepsize 0.5
array5=np.arange(2,10,0.5,dtype=float)
print(array5)

[2. 3. 4. 5. 6. 7. 8. 9.]
[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


np.linspace():
numpy.linspace() is used to generate an array of evenly spaced numbers over a specified range.

Parameters:

1.start (required): The starting value of the sequence.

2.stop (required): The end value of the sequence.

3.num (optional, default=50): Number of values to generate.

4.endpoint (optional, default=True): If True, includes stop; if False, excludes it.
5.retstep (optional, default=False): If True, returns the step size along with the array.

6.dtype (optional): Specifies the data type of the output array.



Syntax:

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)


In [131]:
array6=np.linspace(2,5,num=5,dtype=float)
print(array6)

[2.   2.75 3.5  4.25 5.  ]


Slicing Numpy Arrays


np_array_name[start_index,end_index]: slices a numpy array from start to end index(does not include last index)

In [132]:
np1=np.array([3,-1,0,1,2,3,4,5,6,7,8,9]);

print(np1[1:5])#slicing an list same as python

[-1  0  1  2]


Return from somthing till the end of the array
np_array_name[start_index: ]

In [133]:
print(np1[4:])

[2 3 4 5 6 7 8 9]


Negative index:

In [134]:
print(np1[-3:-1])

[7 8]


Steping across elements


In [135]:
print(np1[2:7:2])

[0 2 4]


Slicing 2d array

In [136]:
np2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


numpy_array_name[start_row:end_row,start_column:end_column]

-> elements starting from start row and ending one before the end row.

->Similarly for columns

In [137]:
print(np2d[0:1,1:3])#excludes row 1 so slices only 0th row

[[2 3]]


In [138]:
print(np2d[0:2,1:3])#excludes row 2(does not exists) so slices noly 0th and 1st rows

[[2 3]
 [7 8]]


In [139]:
np3d=np.array([[[1,2,3],[4,5,6,],[7,8,9],[10,11,12]]])#creating a 3d array

Universal Functions in Numpy

Square Root of each elements

np.sqrt(numpy_array)

In [140]:
print(np.sqrt(np1))

[1.73205081        nan 0.         1.         1.41421356 1.73205081
 2.         2.23606798 2.44948974 2.64575131 2.82842712 3.        ]


<ipython-input-140-021a376fbfc6>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(np1))


Absolute Value of a function

np.absolute(numpy_array)

In [141]:
print(np.absolute(np1))

[3 1 0 1 2 3 4 5 6 7 8 9]


Exponents:

np.exp(np1)

In [142]:
print(np.exp(np1))

[2.00855369e+01 3.67879441e-01 1.00000000e+00 2.71828183e+00
 7.38905610e+00 2.00855369e+01 5.45981500e+01 1.48413159e+02
 4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03]


Min/Max:

np.max(array_name)

np.min(array_name)

In [143]:
print(np.max(np1))
print(np.min(np1))

9
-1


Sign:

positive or negative

In [144]:
print(np.sign(np1))

[ 1 -1  0  1  1  1  1  1  1  1  1  1]


Trignonometric and logarithmic functions


In [145]:
print(np.sin(np1))
print(np.cos(np1))
print(np.tan(np1))
print(np.log(np1))

[ 0.14112001 -0.84147098  0.          0.84147098  0.90929743  0.14112001
 -0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
[-0.9899925   0.54030231  1.          0.54030231 -0.41614684 -0.9899925
 -0.65364362  0.28366219  0.96017029  0.75390225 -0.14550003 -0.91113026]
[-0.14254654 -1.55740772  0.          1.55740772 -2.18503986 -0.14254654
  1.15782128 -3.38051501 -0.29100619  0.87144798 -6.79971146 -0.45231566]
[1.09861229        nan       -inf 0.         0.69314718 1.09861229
 1.38629436 1.60943791 1.79175947 1.94591015 2.07944154 2.19722458]


<ipython-input-145-fee436291549>:4: RuntimeWarning: divide by zero encountered in log
  print(np.log(np1))
<ipython-input-145-fee436291549>:4: RuntimeWarning: invalid value encountered in log
  print(np.log(np1))


Copy vs View


View: Changes made in original array reflected in the secondary array


View syntax

new_array=original_array.view()

In [146]:
np2=np1.view()

print(f'Original NP1 {np1}')
print(f'Original NP2 {np2}')

np1[0]=41

print(f'Modified NP1 {np1}')
print(f'Modified NP2 {np2}')


Original NP1 [ 3 -1  0  1  2  3  4  5  6  7  8  9]
Original NP2 [ 3 -1  0  1  2  3  4  5  6  7  8  9]
Modified NP1 [41 -1  0  1  2  3  4  5  6  7  8  9]
Modified NP2 [41 -1  0  1  2  3  4  5  6  7  8  9]


In case of view(),any change made in the new array will also be reflected in the original array

In [147]:
np2[1]=90
print(f'Modified NP1 {np1}')
print(f'Modified NP2 {np2}')


Modified NP1 [41 90  0  1  2  3  4  5  6  7  8  9]
Modified NP2 [41 90  0  1  2  3  4  5  6  7  8  9]


Copy: Change in original is not reflected in the copied array

Copy Syntax:
new_array=original_array.copy()

In [148]:
np3=np1.copy()

print(f'Original NP1 {np1}')
print(f'Original NP3 {np3}')

np1[0]=42

print(f'Modified NP1 {np1}')
print(f'Modified NP3 {np3}')

Original NP1 [41 90  0  1  2  3  4  5  6  7  8  9]
Original NP3 [41 90  0  1  2  3  4  5  6  7  8  9]
Modified NP1 [42 90  0  1  2  3  4  5  6  7  8  9]
Modified NP3 [41 90  0  1  2  3  4  5  6  7  8  9]


Shape and Reshape Numpy Arrays

To find the shape of a numpy array we use:

'array_name.shape' function

For one dimensional array it simply prints number of elements in the array

In [149]:
print(np1.shape)

(12,)


In two dimensional array it returns

(no. of rows,no. of columns)

In [150]:
print(np2.shape)

(12,)


Reshaping :

array_name.reshape(new_no_of rows,new_no_of columns)

In [151]:
print(np1.reshape(3,4))# reshaping 1D array into 2D array

[[42 90  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]


In [152]:
print(np1.reshape(3,2,2))# reshaping 1D array into 3 Darray

[[[42 90]
  [ 0  1]]

 [[ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]]]


In [153]:
print(np2.reshape(-1))#flattening a 2D array into 1D array

[42 90  0  1  2  3  4  5  6  7  8  9]


Iterating through Numpy Arrays


In [154]:
for x in np1:
  print(x)#1d arrays

42
90
0
1
2
3
4
5
6
7
8
9


In [155]:
for x in np2d:
  print(x)#2d arrays

[1 2 3 4 5]
[ 6  7  8  9 10]


In [156]:
for x in np2d:
  for y in x:
    print(y)#each element of a row

1
2
3
4
5
6
7
8
9
10


In [157]:
for x in np3d:
  for y in x:
    for z in y:
      print(z)#each element of row in 3d array

1
2
3
4
5
6
7
8
9
10
11
12


np.nditer() function

Iterates through the basic units of whichever dimensional array present

In [158]:
for x in np.nditer(np3d):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


Sorting numpy arrays

np.sort()

does not change the original array, prints a copy

In [159]:
unsorted=np.array([5,3,5,2,7,8,10,4,9])
print(unsorted)
print(np.sort(unsorted))

[ 5  3  5  2  7  8 10  4  9]
[ 2  3  4  5  5  7  8  9 10]


In [160]:
char=np.array(["abc","wef","hyt","eqwr","powep"])
print(np.sort(char))

['abc' 'eqwr' 'hyt' 'powep' 'wef']


In [161]:
boolean=np.array([True,False,False,True,True])
print(np.sort(boolean))

[False False  True  True  True]


Searching Numpy

In [162]:
a=np.where(np1==3)
print(a[0])

[5]


In [163]:
#To find the even numbers
b=np.where(np1 % 2==0)
print(b[0])

[ 0  1  2  4  6  8 10]


In [164]:
#To find odd numbers
c=np.where(np1%2==1);
print(c[0])

[ 3  5  7  9 11]


Filtering Numpy Arrays

In [165]:
x=[True,True,False,True,False,False,False,True,True,False,False,True]
print(np1[x])

[42 90  1  5  6  9]


Creating a list by appyling some logic to determine whether the array element will be true or false

In [166]:
filtered=[]
for thing in np1:
  if thing % 2==0:
      filtered.append(True)
  else:
    filtered.append(False)

print(filtered)

[True, True, True, False, True, False, True, False, True, False, True, False]


In [167]:
print(np1[filtered])

[42 90  0  2  4  6  8]


In [168]:
filter=np1%2==0
print(filter)
print(np1[filter])

[ True  True  True False  True False  True False  True False  True False]
[42 90  0  2  4  6  8]
